# Generated by Django 5.2.7 on 2025-10-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransportApprove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=20, unique=True)),
                ('transport', models.CharField(choices=[('Transport 1', 'Transport 1'), ('Transport 2', 'Transport 2'), ('Transport 3', 'Transport 3')], max_length=50)),
                ('warehouse', models.CharField(choices=[('WH Cox Raw', 'WH Cox Raw'), ('WH Cox FG', 'WH Cox FG'), ('WH Dhaka Raw', 'WH Dhaka Raw'), ('WH Dhaka FG', 'WH Dhaka FG'), ('R&D Center, FG', 'R&D Center, FG'), ('R&D Center, RAW', 'R&D Center, RAW')], max_length=50)),
                ('address', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
