# Generated by Django 5.2.7 on 2025-10-19 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lc_number', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('correction_id', models.CharField(max_length=100)),
                ('mother_vessel', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=200)),
                ('lc_quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('edit_quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('edit_lc_trader', models.CharField(max_length=200)),
                ('edit_reg_no', models.CharField(max_length=100)),
                ('edit_allot_lc', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DOChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('log_center', models.CharField(choices=[('Admin', 'Admin'), ('Noapara', 'Noapara'), ('Nagarbari', 'Nagarbari'), ('Chittagong', 'Chittagong'), ('Narayanganj', 'Narayanganj'), ('Ashugang', 'Ashugang'), ('Dhaka', 'Dhaka')], max_length=20)),
                ('do_number', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=200)),
                ('sale_detail', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('lc_number', models.CharField(max_length=100)),
                ('dv_from', models.CharField(max_length=200)),
                ('godown', models.CharField(max_length=200)),
                ('gudam', models.CharField(max_length=200)),
                ('delivery_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LVActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lc_number', models.CharField(max_length=100)),
                ('lighter_vessel', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=20)),
                ('mv', models.CharField(max_length=200)),
                ('cary_id', models.CharField(max_length=100)),
                ('lighter_freight', models.DecimalField(decimal_places=2, max_digits=15)),
                ('srv_id', models.CharField(max_length=100)),
                ('survey_bill', models.DecimalField(decimal_places=2, max_digits=15)),
                ('load_quan_asper_survey', models.DecimalField(decimal_places=2, max_digits=15)),
                ('actual_received_quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payable_quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('time_not_to_count', models.CharField(max_length=100)),
                ('cause', models.TextField()),
                ('short_ex', models.CharField(max_length=100)),
                ('charpatra_date', models.DateField()),
                ('load_start_time', models.DateTimeField()),
                ('load_complete_time', models.DateTimeField()),
                ('sailing_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('discharge_start_time', models.DateTimeField()),
                ('discharge_complete_time', models.DateTimeField()),
                ('sale_center', models.CharField(max_length=200)),
                ('landing_ghat_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotherToLighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lc_number', models.CharField(max_length=100)),
                ('mother_vessel', models.CharField(max_length=200)),
                ('lighter_vessel', models.CharField(max_length=200)),
                ('carrying_contractor', models.CharField(max_length=200)),
                ('product_info', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('arrival_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GhatToDump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lc_number', models.CharField(max_length=100)),
                ('lighter_vessel', models.CharField(max_length=200)),
                ('product_info', models.CharField(max_length=200)),
                ('update_date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.dump')),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.godown')),
            ],
        ),
        migrations.CreateModel(
            name='LighterToGhat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lc_number', models.CharField(max_length=100)),
                ('lighter_vessel', models.CharField(max_length=200)),
                ('product_info', models.CharField(max_length=200)),
                ('moving_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.godown')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_info', models.CharField(max_length=200)),
                ('lc_number', models.CharField(max_length=100)),
                ('transfer_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_dump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_transfers', to='manage_app.dump')),
                ('from_godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_transfers', to='manage_app.godown')),
                ('to_dump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_transfers', to='manage_app.dump')),
                ('to_godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_transfers', to='manage_app.godown')),
            ],
        ),
    ]
