# Generated by Django 5.2.7 on 2025-10-19 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=20, unique=True)),
                ('route_name', models.CharField(max_length=200)),
                ('tr_code', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('thana', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=20)),
                ('location_detail', models.TextField()),
                ('status', models.CharField(default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ASM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asm_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=20)),
                ('asm_code', models.CharField(max_length=50)),
                ('zone_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpo_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsm_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('rsm_code', models.CharField(max_length=50)),
                ('region_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sm_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('sm_code', models.CharField(max_length=50)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.CharField(max_length=20, unique=True)),
                ('depo', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='distributor.asm')),
                ('mpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='distributor.mpo')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='distributor.area')),
                ('rsm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='distributor.rsm')),
                ('sm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='distributor.sm')),
            ],
        ),
    ]
