# Generated by Django 5.2.7 on 2025-10-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Sale', 'Sale'), ('Purchase', 'Purchase'), ('Bank', 'Bank'), ('Cash', 'Cash'), ('Journal', 'Journal'), ('Allotment', 'Allotment')], max_length=10)),
                ('transaction_id', models.CharField(max_length=100)),
                ('updated_fields', models.JSONField()),
                ('old_values', models.JSONField()),
                ('new_values', models.JSONField()),
                ('updated_by', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
