# Generated by Django 5.2.7 on 2025-10-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_today', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sales_week', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sales_month', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('production_yesterday', models.IntegerField(default=0)),
                ('production_week', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Dashboard Statistics',
            },
        ),
    ]
