# Generated by Django 5.2.7 on 2025-10-19 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('thana', models.CharField(max_length=100)),
                ('dealer_registration', models.CharField(max_length=100)),
                ('dealer_contact', models.CharField(max_length=20)),
                ('dealer_address', models.TextField()),
                ('status', models.CharField(default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllotmentSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allotment_id', models.CharField(max_length=20, unique=True)),
                ('district', models.CharField(max_length=100)),
                ('thana', models.CharField(max_length=100)),
                ('lc_number', models.CharField(max_length=100)),
                ('product_info', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('agri_ir', models.CharField(max_length=100)),
                ('agri_ir_date', models.DateField()),
                ('balance_qty_in_bag', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sale_qty_in_bag', models.DecimalField(decimal_places=2, max_digits=15)),
                ('m_ton', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity_in_m_ton', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('delivery_product', models.CharField(max_length=200)),
                ('delivery_from', models.CharField(choices=[('Mother Vessel', 'Mother Vessel'), ('Lighter Vessel', 'Lighter Vessel'), ('Godown', 'Godown')], max_length=20)),
                ('godown', models.CharField(max_length=200)),
                ('status_type', models.CharField(choices=[('Material', 'Material'), ('Paper', 'Paper')], max_length=10)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allotment.dealer')),
            ],
        ),
    ]
