# Generated by Django 5.2.7 on 2025-10-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('Accounts Report', 'Accounts Report'), ('Cash Report', 'Cash Report'), ('Sale Report', 'Sale Report'), ('Bank Report', 'Bank Report'), ('Admin Report', 'Admin Report'), ('Warehouse Report', 'Warehouse Report'), ('Allotment Report', 'Allotment Report'), ('Journal Report', 'Journal Report')], max_length=50)),
                ('generated_by', models.CharField(max_length=100)),
                ('parameters', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.IntegerField(default=0)),
            ],
        ),
    ]
