# Generated by Django 5.2.7 on 2025-10-19 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Local', 'Local'), ('Overseas', 'Overseas'), ('Both', 'Both')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('reg_number', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('exporter_info', models.TextField()),
                ('registration_no', models.CharField(max_length=100)),
                ('mother_vessel', models.CharField(max_length=200)),
                ('lc_bank', models.CharField(max_length=200)),
                ('lc_bank_branch', models.CharField(max_length=200)),
                ('exporter_country', models.CharField(max_length=100)),
                ('lc_account', models.CharField(max_length=100)),
                ('lc_number', models.CharField(max_length=100, unique=True)),
                ('allot_lc_number', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('lc_open_date', models.DateField()),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Pending', 'Pending'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lc_manage.consignee')),
            ],
        ),
    ]
