# Generated by Django 5.2.7 on 2025-10-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransferManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_id', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField()),
                ('from_location', models.CharField(choices=[('WH Cox Raw', 'WH Cox Raw'), ('WH Cox FG', 'WH Cox FG'), ('WH Dhaka Raw', 'WH Dhaka Raw'), ('WH Dhaka FG', 'WH Dhaka FG'), ('R&D Center, FG', 'R&D Center, FG'), ('R&D Center, RAW', 'R&D Center, RAW')], max_length=20)),
                ('to_location', models.CharField(choices=[('WH Cox Raw', 'WH Cox Raw'), ('WH Cox FG', 'WH Cox FG'), ('WH Dhaka Raw', 'WH Dhaka Raw'), ('WH Dhaka FG', 'WH Dhaka FG'), ('R&D Center, FG', 'R&D Center, FG'), ('R&D Center, RAW', 'R&D Center, RAW')], max_length=20)),
                ('product_type', models.CharField(choices=[('Finish', 'Finish'), ('Raw', 'Raw')], max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Received', 'Received')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
