# Generated by Django 5.2.7 on 2025-10-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petty_cash_id', models.CharField(max_length=20, unique=True)),
                ('account', models.CharField(max_length=200)),
                ('transaction_type', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('note', models.TextField()),
                ('description', models.TextField()),
                ('voucher_number', models.CharField(max_length=100)),
                ('lc_number', models.CharField(max_length=100)),
                ('entry_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Audited', 'Audited'), ('Confirmed', 'Confirmed')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
