# Generated by Django 5.2.7 on 2025-10-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_id', models.CharField(max_length=20, unique=True)),
                ('account_name', models.CharField(max_length=200)),
                ('receive_bank_name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('TT', 'TT'), ('BFTN(Queue)', 'BFTN(Queue)'), ('Cheque(Queue)', 'Cheque(Queue)'), ('NPBS(Instant)', 'NPBS(Instant)'), ('RTGS(Instant)', 'RTGS(Instant)'), ('Advice', 'Advice')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('note', models.TextField()),
                ('description', models.TextField()),
                ('entry_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CashReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_id', models.CharField(max_length=20, unique=True)),
                ('account_name', models.CharField(max_length=200)),
                ('receive_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('receive_note', models.TextField()),
                ('description', models.TextField()),
                ('voucher_number', models.CharField(max_length=100)),
                ('entry_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DealerBankReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_id', models.CharField(max_length=20, unique=True)),
                ('district', models.CharField(max_length=100)),
                ('thana', models.CharField(max_length=100)),
                ('dealer', models.CharField(max_length=200)),
                ('receive_bank_name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('TT', 'TT'), ('BFTN(Queue)', 'BFTN(Queue)'), ('Cheque(Queue)', 'Cheque(Queue)'), ('NPBS(Instant)', 'NPBS(Instant)'), ('RTGS(Instant)', 'RTGS(Instant)'), ('Advice', 'Advice')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('note', models.TextField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
