# Generated by Django 5.2.7 on 2025-10-19 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('entry_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Godown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ghat', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('Self', 'Self'), ('Other', 'Other')], max_length=10)),
                ('sales_hub', models.CharField(choices=[('Admin', 'Admin'), ('Nowapara', 'Nowapara'), ('Nagarbari', 'Nagarbari'), ('Chittagong', 'Chittagong'), ('Narayanganj', 'Narayanganj'), ('Ashugang', 'Ashugang'), ('Dhaka', 'Dhaka')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Fertilizer', 'Fertilizer'), ('Food Grains', 'Food Grains'), ('Cement', 'Cement'), ('Mineral', 'Mineral'), ('Other', 'Other')], max_length=20)),
                ('product_group', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('title_bengali', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('unit_type', models.CharField(choices=[('KG', 'KG'), ('Bag', 'Bag')], max_length=10)),
                ('unit_strength', models.DecimalField(decimal_places=2, max_digits=10)),
                ('open_sale_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('allotment_sale_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.godown')),
            ],
        ),
    ]
