# Generated by Django 5.2.7 on 2025-10-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.CharField(max_length=200)),
                ('zone', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Sale Create', 'Sale Create'), ('Sale Audit', 'Sale Audit'), ('Sale Approve', 'Sale Approve'), ('Sale Cancel', 'Sale Cancel'), ('Sale Delivery', 'Sale Delivery'), ('Purchase Create', 'Purchase Create'), ('Purchase Audit', 'Purchase Audit'), ('Purchase Cancel', 'Purchase Cancel'), ('Purchase Approve', 'Purchase Approve'), ('Purchase Finish Create', 'Purchase Finish Create'), ('Purchase Finish Approve', 'Purchase Finish Approve'), ('Production Create', 'Production Create'), ('Production Qc', 'Production Qc'), ('Production Approve', 'Production Approve'), ('Production Raw', 'Production Raw'), ('Transfer Create', 'Transfer Create'), ('Transfer Approve', 'Transfer Approve'), ('Transfer Receive', 'Transfer Receive'), ('Cash Receive', 'Cash Receive'), ('Cash Payment', 'Cash Payment')], max_length=50)),
                ('emails', models.TextField(help_text='Comma separated email addresses')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinishProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_title', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
